development:
  adapter: postgresql
  encoding: unicode
  database: socialshare_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: socialshare_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: socialshare_production
  pool: 5
  username:
  password: